name: Shipping CICD - Dev Branch
run-name: Shipping CICD - Dev Branch
on:
  push:
    branches:
      - 'RB-**'
jobs:
  ci:
    uses: VenkatBheemireddyOrg/github-reusable-actions/.github/workflows/ci-dev-branch.yml@main
    with:
      component: shipping
      appType: nodejs
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
