name: Shipping CICD
run-name: Shipping CICD
on: [push]
jobs:
  ci:
    uses: VenkatBheemireddyOrg/github-reusable-actions/.github/workflows/ci.yml@main
    with:
      component: shipping
      appType: maven
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

  deploy:
    needs: ci
    uses: VenkatBheemireddyOrg/github-reusable-actions/.github/workflows/deploy.yml@main
    with:
      component: shipping




